export enum AuditActionType {
  AUTH_LOGIN_SUCCESS = "auth.login_success",
  AUTH_LOGIN_FAILED = "auth.login_failed",
  AUTH_LOGOUT = "auth.logout",
  TASK_CREATED = "tasks.created",
  TASK_UPDATED = "tasks.updated",
  TASK_DELETED = "tasks.deleted",
  TASK_COMPLETED = "tasks.completed",
  TASK_UNCOMPLETED = "tasks.uncompleted",
  TASK_RECURRENCE_CHANGED = "tasks.recurrence_changed",
  PROJECT_CREATED = "projects.created",
  PROJECT_UPDATED = "projects.updated",
  PROJECT_DELETED = "projects.deleted",
  PROJECT_MEMBERS_UPDATED = "projects.members_updated",
  USER_CREATED = "users.created",
  USER_UPDATED = "users.updated",
  USER_ARCHIVED = "users.archived",
  USER_RESTORED = "users.restored",
  API_TOKEN_CREATED = "api_tokens.created",
  API_TOKEN_DELETED = "api_tokens.deleted",
  TIMELOG_CREATED = "timelogs.created",
  TIMELOG_UPDATED = "timelogs.updated",
  TIMELOG_DELETED = "timelogs.deleted",
}
