export enum PAGE_NAMES {
  'project-detail' = 'project-detail',
  home = 'home',
  projects = 'projects',
  planning = 'planning',
  report = 'report',
  USERS_MANAGEMENT = 'users-management',
  CHAT = 'chat',
  projectsIdWiki = 'projects-project_id-wiki-page',
  projectReport = 'project-report',
  docContent = 'doc-content',
  wiki = 'wiki',
  projectsProjectIdWikiPagePageId = 'projects-project_id-wiki-page-page_id',
  CHANGELOGS = 'changelogs',
  AUDIT_LOGS = 'audit-logs',
  HEALTHCHECKS = 'healthchecks',
  SCHEDULE = 'schedule',
  MAIL = 'mail',
  MAIL_ACCOUNTS = 'mail-accounts',
  GIT = 'git',
}
