export enum SOCKET_EVENT_TYPE {
  task_added = 'task_added',
  task_update = 'task_update',
  task_deleted = 'task_deleted',
  notification_added = 'notification_added',
  notification_updated = 'notification_updated',
  comment_added = 'comment_added',
  comment_deleted = 'comment_deleted',
  comment_updated = 'comment_updated',
  chat_message_added = 'chat_message_added',
  chat_message_deleted = 'chat_message_deleted',
  chat_message_updated = 'chat_message_updated',
  chat_deleted = 'chat_deleted',
  user_online = 'user_online',
  user_offline = 'user_offline',
  users_online = 'users_online',
  timelog_updated = 'timelog_updated',
  timelog_deleted = 'timelog_deleted',
}
